fix build issue "react-lite-youtube-embed": "2.4.0"
"react-lite-youtube-embed" 2.5.0 & 2.5.1 breaks things (for build but OK in dev)
error: requested module 'react-lite-youtube-embed' does not provide an export named 'default'
works with 2.4.0
also update some more mangled images